### ISSUE TITLE
Todo: Domingo

### ISSUE THREAD

**Issue by SamuelLimaCap** [pzambaoifsp/frontend-ag#3]
**IMPORTANTES**
- [x] Tela para visualização dos detalhes da banca
- [x] Tela para edição da banca
  - [ ] Atenção nesse tópico, não tem como editar os admins da banca na rota de UPDATE. Tem 2 rotas específicas para adicionar e remover admins nas bancas (achou ruim entao xinga o caio)
- [x] hospedar o frontend no netifly ou no heroku

Menos importantes:
- [ ] Exibição no formato de calendário

Pequenos problemas:
- [x] A conta de emails foi desativada por spam kkkkkk. Vou ter que providenciar outra
- [x] Na página de registrar, o campo "Nome de usuário" nao permite colocar o nome completo, ta correto?
- Sim/não, não entendi se era um username tipo nickname ou nome mesmo

- [x] Na página de criação de banca, tive que alterar a ordem dos inputs, mas nao alterei a ordem dos labels na esquerda
